/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectManager_Module;

import Login.LoginForm;

/**
 *
 * @author amr
 */
public class ProjectManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form PM
     */
    public ProjectManagerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        writereport = new javax.swing.JButton();
        assproject = new javax.swing.JButton();
        pmattendance = new javax.swing.JButton();
        projectprograss = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(651, 451));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Project Manager");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 300, 60);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 50, 160, 180);

        writereport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        writereport.setText("Write Report to TM about employee");
        writereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writereportActionPerformed(evt);
            }
        });
        getContentPane().add(writereport);
        writereport.setBounds(100, 180, 440, 50);

        assproject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assproject.setText("Add Project");
        assproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assprojectActionPerformed(evt);
            }
        });
        getContentPane().add(assproject);
        assproject.setBounds(20, 80, 280, 50);

        pmattendance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pmattendance.setText("Attendance");
        pmattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmattendanceActionPerformed(evt);
            }
        });
        getContentPane().add(pmattendance);
        pmattendance.setBounds(170, 270, 280, 50);

        projectprograss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        projectprograss.setText("View Project Prograss");
        projectprograss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectprograssActionPerformed(evt);
            }
        });
        getContentPane().add(projectprograss);
        projectprograss.setBounds(350, 80, 280, 50);

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("Log out");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(350, 340, 160, 50);

        exit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit1.setText("Exit");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1);
        exit1.setBounds(120, 340, 160, 50);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        LoginForm log=new LoginForm();
        log.setVisible(true);
        this.setVisible(false);           // TODO add your handling code here:
       
    }//GEN-LAST:event_exitActionPerformed

    private void writereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writereportActionPerformed
        // TODO add your handling code here:
        PMSendReport p=new PMSendReport();
        p.setLocation(400, 150);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_writereportActionPerformed

    private void pmattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmattendanceActionPerformed
        // TODO add your handling code here:
        PMViewAttendance p=new PMViewAttendance();
        p.setLocation(400, 150);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pmattendanceActionPerformed

    private void assprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assprojectActionPerformed
        // TODO add your handling code here:
        Add_project p=new Add_project();
        p.setLocation(400, 150);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assprojectActionPerformed

    private void projectprograssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectprograssActionPerformed
        // TODO add your handling code here:
        PMViewPrograssofProject p=new PMViewPrograssofProject();
        p.setLocation(400, 150);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectprograssActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assproject;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pmattendance;
    private javax.swing.JButton projectprograss;
    private javax.swing.JButton writereport;
    // End of variables declaration//GEN-END:variables
}
